package instructor.oracle.apps.ak.first.server;

import instructor.oracle.apps.ak.schema.server.AddressEOImpl;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AddressVORowImpl extends OAViewRowImpl {
    public static final int ADDRESSID = 0;
    public static final int ADDRESSNAME = 1;
    public static final int ADDRESSLINE1 = 2;
    public static final int TOWNORCITY = 3;

    /**This is the default constructor (do not remove)
     */
    public AddressVORowImpl() {
    }

    /**Gets AddressEO entity object.
     */
    public AddressEOImpl getAddressEO() {
        return (AddressEOImpl)getEntity(0);
    }

    /**Gets the attribute value for ADDRESS_ID using the alias name AddressId
     */
    public Number getAddressId() {
        return (Number) getAttributeInternal(ADDRESSID);
    }

    /**Sets <code>value</code> as attribute value for ADDRESS_ID using the alias name AddressId
     */
    public void setAddressId(Number value) {
        setAttributeInternal(ADDRESSID, value);
    }

    /**Gets the attribute value for ADDRESS_NAME using the alias name AddressName
     */
    public String getAddressName() {
        return (String) getAttributeInternal(ADDRESSNAME);
    }

    /**Sets <code>value</code> as attribute value for ADDRESS_NAME using the alias name AddressName
     */
    public void setAddressName(String value) {
        setAttributeInternal(ADDRESSNAME, value);
    }

    /**Gets the attribute value for ADDRESS_LINE_1 using the alias name AddressLine1
     */
    public String getAddressLine1() {
        return (String) getAttributeInternal(ADDRESSLINE1);
    }

    /**Sets <code>value</code> as attribute value for ADDRESS_LINE_1 using the alias name AddressLine1
     */
    public void setAddressLine1(String value) {
        setAttributeInternal(ADDRESSLINE1, value);
    }

    /**Gets the attribute value for TOWN_OR_CITY using the alias name TownOrCity
     */
    public String getTownOrCity() {
        return (String) getAttributeInternal(TOWNORCITY);
    }

    /**Sets <code>value</code> as attribute value for TOWN_OR_CITY using the alias name TownOrCity
     */
    public void setTownOrCity(String value) {
        setAttributeInternal(TOWNORCITY, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ADDRESSID:
            return getAddressId();
        case ADDRESSNAME:
            return getAddressName();
        case ADDRESSLINE1:
            return getAddressLine1();
        case TOWNORCITY:
            return getTownOrCity();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ADDRESSID:
            setAddressId((Number)value);
            return;
        case ADDRESSNAME:
            setAddressName((String)value);
            return;
        case ADDRESSLINE1:
            setAddressLine1((String)value);
            return;
        case TOWNORCITY:
            setTownOrCity((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
