package instructor.oracle.apps.ak.schema.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeVVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public EmployeeVVOImpl() {
    }

    public void initQuery(Number employeeId) {
        setWhereClauseParams(null); //Always reset
        setWhereClauseParam(0, employeeId);
        executeQuery();
    }

}
