package instructor.oracle.apps.ak.schema.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PositionVVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public PositionVVOImpl() {
    }

    public void initQuery(String positionCode) {
        setWhereClauseParams(null); // Always reset
        setWhereClauseParam(0, positionCode);
        executeQuery();
    }

}
