package instructor.oracle.apps.ak.employee.server;

import instructor.oracle.apps.ak.schema.server.EmployeeEOImpl;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AllEmployeesVORowImpl extends OAViewRowImpl {
    public static final int EMPLOYEEID = 0;
    public static final int FIRSTNAME = 1;
    public static final int LASTNAME = 2;
    public static final int EMPLOYEENAME = 3;
    public static final int EMPLOYEEEMAIL = 4;
    public static final int MANAGERID = 5;
    public static final int MANAGERNAME = 6;
    public static final int MANAGEREMAIL = 7;
    public static final int POSITIONDISPLAY = 8;
    public static final int DELETESWITCHER = 9;
    public static final int EMPLOYEESTATUS = 10;

    /**This is the default constructor (do not remove)
     */
    public AllEmployeesVORowImpl() {
    }

    /**Gets EmployeeEO entity object.
     */
    public EmployeeEOImpl getEmployeeEO() {
        return (EmployeeEOImpl)getEntity(0);
    }

    /**Gets EmployeeEO1 entity object.
     */
    public EmployeeEOImpl getEmployeeEO1() {
        return (EmployeeEOImpl)getEntity(1);
    }

    /**Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId
     */
    public Number getEmployeeId() {
        return (Number) getAttributeInternal(EMPLOYEEID);
    }

    /**Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name EmployeeId
     */
    public void setEmployeeId(Number value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**Gets the attribute value for FULL_NAME using the alias name EmployeeName
     */
    public String getEmployeeName() {
        return (String) getAttributeInternal(EMPLOYEENAME);
    }

    /**Sets <code>value</code> as attribute value for FULL_NAME using the alias name EmployeeName
     */
    public void setEmployeeName(String value) {
        setAttributeInternal(EMPLOYEENAME, value);
    }

    /**Gets the attribute value for EMAIL_ADDRESS using the alias name EmployeeEmail
     */
    public String getEmployeeEmail() {
        return (String) getAttributeInternal(EMPLOYEEEMAIL);
    }

    /**Sets <code>value</code> as attribute value for EMAIL_ADDRESS using the alias name EmployeeEmail
     */
    public void setEmployeeEmail(String value) {
        setAttributeInternal(EMPLOYEEEMAIL, value);
    }

    /**Gets the attribute value for EMPLOYEE_ID using the alias name ManagerId
     */
    public Number getManagerId() {
        return (Number) getAttributeInternal(MANAGERID);
    }

    /**Gets the attribute value for FULL_NAME using the alias name ManagerName
     */
    public String getManagerName() {
        return (String) getAttributeInternal(MANAGERNAME);
    }

    /**Gets the attribute value for EMAIL_ADDRESS using the alias name ManagerEmail
     */
    public String getManagerEmail() {
        return (String) getAttributeInternal(MANAGEREMAIL);
    }

    /**Gets the attribute value for the calculated attribute PositionDisplay
     */
    public String getPositionDisplay() {
        return (String) getAttributeInternal(POSITIONDISPLAY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PositionDisplay
     */
    public void setPositionDisplay(String value) {
        setAttributeInternal(POSITIONDISPLAY, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EMPLOYEEID:
            return getEmployeeId();
        case FIRSTNAME:
            return getFirstName();
        case LASTNAME:
            return getLastName();
        case EMPLOYEENAME:
            return getEmployeeName();
        case EMPLOYEEEMAIL:
            return getEmployeeEmail();
        case MANAGERID:
            return getManagerId();
        case MANAGERNAME:
            return getManagerName();
        case MANAGEREMAIL:
            return getManagerEmail();
        case POSITIONDISPLAY:
            return getPositionDisplay();
        case DELETESWITCHER:
            return getDeleteSwitcher();
        case EMPLOYEESTATUS:
            return getEmployeeStatus();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EMPLOYEEID:
            setEmployeeId((Number)value);
            return;
        case FIRSTNAME:
            setFirstName((String)value);
            return;
        case LASTNAME:
            setLastName((String)value);
            return;
        case EMPLOYEENAME:
            setEmployeeName((String)value);
            return;
        case EMPLOYEEEMAIL:
            setEmployeeEmail((String)value);
            return;
        case POSITIONDISPLAY:
            setPositionDisplay((String)value);
            return;
        case DELETESWITCHER:
            setDeleteSwitcher((String)value);
            return;
        case EMPLOYEESTATUS:
            setEmployeeStatus((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute FirstName
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FirstName
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**Gets the attribute value for the calculated attribute LastName
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**Gets the attribute value for the calculated attribute DeleteSwitcher
     */
    public String getDeleteSwitcher() {
        return (String) getAttributeInternal(DELETESWITCHER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DeleteSwitcher
     */
    public void setDeleteSwitcher(String value) {
        setAttributeInternal(DELETESWITCHER, value);
    }

    /**Gets the attribute value for the calculated attribute EmployeeStatus
     */
    public String getEmployeeStatus() {
        return (String) getAttributeInternal(EMPLOYEESTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmployeeStatus
     */
    public void setEmployeeStatus(String value) {
        setAttributeInternal(EMPLOYEESTATUS, value);
    }
}
