package instructor.oracle.apps.ak.employee.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import oracle.apps.fnd.framework.OAException;
import oracle.apps.fnd.common.MessageToken;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpDetailsAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public EmpDetailsAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) { /* package name */
            /* Configuration Name */launchTester("instructor.oracle.apps.ak.employee.server",
                                                 "EmpDetailsAMLocal");
    }

    /**Container's getter for EmployeeDetailsVO1
     */
    public EmployeeDetailsVOImpl getEmployeeDetailsVO1() {
        return (EmployeeDetailsVOImpl)findViewObject("EmployeeDetailsVO1");
    }

    public void initDetails(String employeeNumber) {
        EmployeeDetailsVOImpl vo = getEmployeeDetailsVO1();
        if (vo == null) {
            MessageToken[] errTokens =
            { new MessageToken("OBJECT_NAME", "EmployeeDetailsVO1") };
            throw new OAException("AK", "FWK_TBX_OBJECT_NOT_FOUND", errTokens);
        }
        vo.initQuery(employeeNumber);
    } // end initDetails()
}
