package instructor.oracle.apps.ak.employee.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public EmployeesAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("instructor.oracle.apps.ak.employee.server", /* package name */
      "EmployeesAMLocal" /* Configuration Name */);
    }

    /**Container's getter for AllEmployeesVO1
     */
    public OAViewObjectImpl getAllEmployeesVO1() {
        return (OAViewObjectImpl)findViewObject("AllEmployeesVO1");
    }
}
